/* LittleEnvironment v1.0.0 | Generated by tools/build.js */
/**
 * Deterministic, dependency-free event dispatcher for environment systems.
 */
class EnvironmentEventBus {
  /**
   * Creates an empty event bus.
   */
  constructor() {
    this.listeners = new Map();
  }

  /**
   * Registers a listener and returns an unsubscribe function.
   *
   * @param {string} event Event name.
   * @param {(payload: unknown) => void} listener Listener to invoke.
   * @returns {() => void} Function that removes the listener.
   */
  on(event, listener) {
    if (typeof listener !== 'function') {
      throw new TypeError('An event listener must be a function.');
    }
    const listeners = this.listeners.get(event) ?? new Set();
    listeners.add(listener);
    this.listeners.set(event, listeners);
    return () => this.off(event, listener);
  }

  /**
   * Removes one listener.
   *
   * @param {string} event Event name.
   * @param {(payload: unknown) => void} listener Listener to remove.
   * @returns {boolean} Whether a listener was removed.
   */
  off(event, listener) {
    const listeners = this.listeners.get(event);
    if (!listeners) return false;
    const removed = listeners.delete(listener);
    if (listeners.size === 0) this.listeners.delete(event);
    return removed;
  }

  /**
   * Emits an event to a stable listener snapshot.
   *
   * @param {string} event Event name.
   * @param {unknown} payload Event payload.
   */
  emit(event, payload) {
    const listeners = this.listeners.get(event);
    if (!listeners) return;
    for (const listener of [...listeners]) listener(payload);
  }

  /**
   * Removes every listener, optionally only for one event.
   *
   * @param {string} [event] Event name to clear.
   */
  clear(event) {
    if (event === undefined) this.listeners.clear();
    else this.listeners.delete(event);
  }
}

/**
 * Canonical event names emitted by LittleEnvironment systems.
 *
 * @readonly
 */
const EnvironmentEvents = Object.freeze({
  TIME_TICK: 'time:tick',
  NEW_DAY: 'time:new-day',
  SEASON_CHANGE: 'time:season-change',
  WEATHER_CHANGE: 'weather:change',
  WEATHER_TRANSITION: 'weather:transition',
  VITAL_THRESHOLD: 'survival:vital-threshold',
  EFFECT_APPLIED: 'effect:applied',
  EFFECT_REMOVED: 'effect:removed',
  DAMAGE_RESOLVED: 'combat:damage-resolved',
  LEVEL_UP: 'progression:level-up',
});

/**
 * Deterministic calendar state driven by celestial day rollovers.
 */
class CalendarEngine {
  /**
   * @param {object} [options] Calendar configuration.
   * @param {number} [options.dayCount=1] One-based current day.
   * @param {number} [options.daysPerSeason=30] Days in each season.
   * @param {string[]} [options.seasons] Ordered season names.
   */
  constructor({
    dayCount = 1,
    daysPerSeason = 30,
    seasons = ['spring', 'summer', 'autumn', 'winter'],
  } = {}) {
    if (!Number.isInteger(dayCount) || dayCount < 1) {
      throw new RangeError('Calendar day count must be a positive integer.');
    }
    if (!Number.isInteger(daysPerSeason) || daysPerSeason < 1) {
      throw new RangeError('Days per season must be a positive integer.');
    }
    if (!Array.isArray(seasons) || seasons.length === 0 || seasons.some((season) => !season)) {
      throw new TypeError('A calendar requires at least one named season.');
    }
    this.dayCount = dayCount;
    this.daysPerSeason = daysPerSeason;
    this.seasons = [...seasons];
  }

  /** @returns {number} Zero-based current season index. */
  get seasonIndex() {
    return Math.floor((this.dayCount - 1) / this.daysPerSeason) % this.seasons.length;
  }

  /** @returns {number} Compatibility alias for the current season index. */
  get currentSeasonIndex() { return this.seasonIndex; }

  /** @returns {string} Current season name. */
  get currentSeason() {
    return this.seasons[this.seasonIndex];
  }

  /** @returns {number} One-based current year. */
  get year() {
    return Math.floor((this.dayCount - 1) / (this.daysPerSeason * this.seasons.length)) + 1;
  }

  /** @returns {number} One-based day within the current season. */
  get dayOfSeason() {
    return ((this.dayCount - 1) % this.daysPerSeason) + 1;
  }

  /**
   * Advances a whole number of days and returns each rollover.
   *
   * @param {number} [days=1] Number of days to advance.
   * @returns {Array<object>} Rollover descriptors in chronological order.
   */
  advanceDays(days = 1) {
    if (!Number.isInteger(days) || days < 0) {
      throw new RangeError('Calendar advances must be non-negative whole days.');
    }
    const rollovers = [];
    for (let index = 0; index < days; index += 1) {
      const previousSeasonIndex = this.seasonIndex;
      this.dayCount += 1;
      rollovers.push({
        day: this.dayCount,
        season: this.currentSeason,
        seasonChanged: previousSeasonIndex !== this.seasonIndex,
        year: this.year,
      });
    }
    return rollovers;
  }

  /**
   * Produces a serialisable calendar snapshot.
   *
   * @returns {object} Calendar state.
   */
  serialise() {
    return {
      dayCount: this.dayCount,
      daysPerSeason: this.daysPerSeason,
      seasons: [...this.seasons],
    };
  }

  /**
   * Restores a calendar from a snapshot.
   *
   * @param {object} state Calendar state.
   * @returns {CalendarEngine} Restored calendar.
   */
  static deserialise(state) {
    return new CalendarEngine(state);
  }
}

const TAU = Math.PI * 2;

/**
 * Continuous celestial timekeeper with deterministic day and season transitions.
 */
class CelestialClock {
  /**
   * @param {object} [options] Clock configuration.
   * @param {number} [options.dayDurationSeconds=1200] Real seconds in one game day.
   * @param {number} [options.startNormalisedTime=0.25] Starting fraction of a day.
   * @param {number} [options.startNormalizedTime] American-spelled compatibility alias.
   * @param {CalendarEngine} [options.calendar] Calendar to advance on rollover.
   * @param {EnvironmentEventBus} [options.eventBus] Optional event dispatcher.
   */
  constructor({
    dayDurationSeconds = 1200,
    startNormalisedTime,
    startNormalizedTime,
    calendar,
    eventBus,
    daysPerSeason,
    seasons,
  } = {}) {
    if (!Number.isFinite(dayDurationSeconds) || dayDurationSeconds <= 0) {
      throw new RangeError('A celestial day duration must be greater than zero.');
    }
    const initialTime = startNormalisedTime ?? startNormalizedTime ?? 0.25;
    this.dayDurationSeconds = dayDurationSeconds;
    this.time = CelestialClock.normaliseTime(initialTime);
    this.calendar = calendar ?? new CalendarEngine({ daysPerSeason, seasons });
    this.eventBus = eventBus ?? new EnvironmentEventBus();
    this.subscribers = new Set();
  }

  /** @returns {number} One-based world day. */
  get dayCount() { return this.calendar.dayCount; }
  /** @returns {number} Compatibility alias for the day duration. */
  get dayDuration() { return this.dayDurationSeconds; }
  /** @returns {string} Current season. */
  get currentSeason() { return this.calendar.currentSeason; }
  /** @returns {number} Current calendar year. */
  get year() { return this.calendar.year; }
  /** @returns {boolean} Whether the time lies in the night window. */
  get isNight() { return this.time < 0.22 || this.time >= 0.78; }
  /** @returns {boolean} Whether the time lies in the day window. */
  get isDay() { return !this.isNight; }

  /**
   * Advances continuous time, retaining every day rollover even after a long frame.
   *
   * @param {number} deltaSeconds Real seconds elapsed.
   * @param {number} [timeScale=1] Simulation speed multiplier.
   * @returns {object} Current clock snapshot.
   */
  update(deltaSeconds, timeScale = 1) {
    if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) {
      throw new RangeError('Clock delta seconds must be finite and non-negative.');
    }
    if (!Number.isFinite(timeScale) || timeScale < 0) {
      throw new RangeError('Clock time scale must be finite and non-negative.');
    }
    const elapsedDays = (deltaSeconds * timeScale) / this.dayDurationSeconds;
    const totalTime = this.time + elapsedDays;
    const rollovers = Math.floor(totalTime);
    this.time = CelestialClock.normaliseTime(totalTime);
    for (const rollover of this.calendar.advanceDays(rollovers)) {
      this.emit(EnvironmentEvents.NEW_DAY, rollover);
      if (rollover.seasonChanged) this.emit(EnvironmentEvents.SEASON_CHANGE, rollover);
    }
    const snapshot = this.snapshot();
    this.emit(EnvironmentEvents.TIME_TICK, snapshot);
    return snapshot;
  }

  /**
   * Sets continuous time without altering the calendar.
   *
   * @param {number} normalisedTime Fraction of a day.
   */
  setTime(normalisedTime) {
    this.time = CelestialClock.normaliseTime(normalisedTime);
  }

  /**
   * Gets local 24-hour time without rounding away continuous precision.
   *
   * @returns {{hour: number, minute: number, second: number}} Clock time.
   */
  getClockTime() {
    const seconds = this.time * 86400;
    const hour = Math.floor(seconds / 3600);
    const minute = Math.floor((seconds % 3600) / 60);
    return { hour, minute, second: Math.floor(seconds % 60) };
  }

  /**
   * Calculates the sun's orbital angle and unit direction.
   *
   * @returns {{angle: number, elevation: number, x: number, y: number}} Sun position.
   */
  getSunPosition() {
    const angle = TAU * (this.time - 0.25);
    return {
      angle,
      elevation: Math.sin(angle),
      x: Math.cos(angle),
      y: Math.sin(angle),
    };
  }

  /**
   * Calculates the moon's opposing orbital position.
   *
   * @returns {{angle: number, elevation: number, x: number, y: number}} Moon position.
   */
  getMoonPosition() {
    const sun = this.getSunPosition();
    return {
      angle: sun.angle + Math.PI,
      elevation: -sun.elevation,
      x: -sun.x,
      y: -sun.y,
    };
  }

  /**
   * Evaluates a bounded, smooth ambient intensity.
   *
   * @param {number} [minimum=0.06] Night-time intensity floor.
   * @returns {number} Ambient intensity.
   */
  getAmbientIntensity(minimum = 0.06) {
    const sun = Math.sin(TAU * (this.time - 0.25)) * 1.2;
    return Math.max(minimum, Math.min(1, sun));
  }

  /**
   * Subscribes to every clock event using the legacy `(event, data)` shape.
   *
   * @param {(event: string, data: object) => void} callback Listener to invoke.
   * @returns {() => void} Function that removes the subscription.
   */
  subscribe(callback) {
    if (typeof callback !== 'function') throw new TypeError('A clock subscriber must be a function.');
    this.subscribers.add(callback);
    return () => this.subscribers.delete(callback);
  }

  /**
   * Dispatches through the event bus and legacy subscriptions.
   *
   * @param {string} event Event name.
   * @param {object} payload Event data.
   */
  emit(event, payload) {
    this.eventBus.emit(event, payload);
    for (const subscriber of [...this.subscribers]) subscriber(event, payload);
  }

  /**
   * Returns a serialisable summary.
   *
   * @returns {object} Clock state.
   */
  snapshot() {
    return {
      time: this.time,
      ...this.getClockTime(),
      dayCount: this.dayCount,
      season: this.currentSeason,
      year: this.year,
      isNight: this.isNight,
    };
  }

  /**
   * Produces a complete clock snapshot for persistence.
   *
   * @returns {object} Clock state.
   */
  serialise() {
    return {
      dayDurationSeconds: this.dayDurationSeconds,
      time: this.time,
      calendar: this.calendar.serialise(),
    };
  }

  /**
   * Restores a clock from serialised state.
   *
   * @param {object} state Clock state.
   * @param {EnvironmentEventBus} [eventBus] Event dispatcher.
   * @returns {CelestialClock} Restored clock.
   */
  static deserialise(state, eventBus) {
    return new CelestialClock({
      dayDurationSeconds: state.dayDurationSeconds,
      startNormalisedTime: state.time,
      calendar: CalendarEngine.deserialise(state.calendar),
      eventBus,
    });
  }

  /**
   * Wraps a number into the continuous half-open day interval.
   *
   * @param {number} value Any finite day fraction.
   * @returns {number} Fraction in [0, 1).
   */
  static normaliseTime(value) {
    if (!Number.isFinite(value)) throw new TypeError('Celestial time must be finite.');
    return ((value % 1) + 1) % 1;
  }
}

const colourClamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));
const normaliseGradientTime = (value) => ((value % 1) + 1) % 1;

/**
 * Cyclic ambient colour palette with linear or smooth Hermite interpolation.
 */
class AmbientColorGradient {
  /**
   * @param {Array<object>} [keyframes] Ordered or unordered palette keyframes.
   * @param {'linear'|'hermite'} [interpolation='linear'] Interpolation mode.
   */
  constructor(keyframes = AmbientColorGradient.defaultKeyframes(), interpolation = 'linear') {
    this.interpolation = interpolation;
    this.setKeyframes(keyframes);
  }

  /**
   * Replaces the colour keyframes.
   *
   * @param {Array<object>} keyframes Palette frames with `t` and `colour` or `c`.
   */
  setKeyframes(keyframes) {
    if (!Array.isArray(keyframes) || keyframes.length < 2) {
      throw new TypeError('An ambient gradient requires at least two keyframes.');
    }
    this.keyframes = keyframes.map((frame) => {
      const source = frame.colour ?? frame.c ?? frame.color;
      if (!source || !Number.isFinite(frame.t)) {
        throw new TypeError('Each ambient keyframe requires finite time and colour values.');
      }
      return {
        t: normaliseGradientTime(frame.t),
        colour: {
          r: colourClamp(Math.round(source.r), 0, 255),
          g: colourClamp(Math.round(source.g), 0, 255),
          b: colourClamp(Math.round(source.b), 0, 255),
          a: colourClamp(Number(source.a ?? 1), 0, 1),
        },
      };
    }).sort((first, second) => first.t - second.t);
  }

  /**
   * Evaluates the palette at a normalised time.
   *
   * @param {number} time Fraction of a day.
   * @returns {{r: number, g: number, b: number, a: number}} RGBA colour.
   */
  evaluate(time) {
    const normalised = normaliseGradientTime(time);
    let previous = this.keyframes[this.keyframes.length - 1];
    let next = this.keyframes[0];
    for (let index = 0; index < this.keyframes.length; index += 1) {
      const candidate = this.keyframes[index];
      if (candidate.t <= normalised) {
        previous = candidate;
        next = this.keyframes[(index + 1) % this.keyframes.length];
      }
    }
    const span = next.t > previous.t ? next.t - previous.t : 1 - previous.t + next.t;
    const distance = normalised >= previous.t ? normalised - previous.t : 1 - previous.t + normalised;
    let progress = span === 0 ? 0 : distance / span;
    if (this.interpolation === 'hermite') progress = progress * progress * (3 - 2 * progress);
    return {
      r: Math.round(previous.colour.r + (next.colour.r - previous.colour.r) * progress),
      g: Math.round(previous.colour.g + (next.colour.g - previous.colour.g) * progress),
      b: Math.round(previous.colour.b + (next.colour.b - previous.colour.b) * progress),
      a: Number((previous.colour.a + (next.colour.a - previous.colour.a) * progress).toFixed(4)),
    };
  }

  /**
   * Returns the built-in day/night palette.
   *
   * @returns {Array<object>} Palette keyframes.
   */
  static defaultKeyframes() {
    return [
      { t: 0, colour: { r: 10, g: 15, b: 35, a: 0.92 } },
      { t: 0.22, colour: { r: 40, g: 30, b: 50, a: 0.85 } },
      { t: 0.28, colour: { r: 230, g: 120, b: 80, a: 0.3 } },
      { t: 0.5, colour: { r: 255, g: 255, b: 240, a: 0 } },
      { t: 0.72, colour: { r: 240, g: 100, b: 50, a: 0.35 } },
      { t: 0.8, colour: { r: 25, g: 20, b: 45, a: 0.88 } },
    ];
  }
}

const boundedLightHash = (text) => {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) / 4294967296;
};

/**
 * Headless description of a deterministic dynamic point light.
 */
class LightSource {
  /**
   * @param {object} [options] Light configuration.
   */
  constructor({
    id = 'light',
    position = { x: 0, y: 0 },
    pos,
    radius = 120,
    colour = { r: 255, g: 180, b: 60 },
    color,
    intensity = 1,
    flickerSpeed = 8,
    flickerAmount = 0.08,
    flickerSeed,
    enabled = true,
  } = {}) {
    if (!Number.isFinite(radius) || radius < 0) throw new RangeError('Light radius must be non-negative.');
    this.id = String(id);
    this.position = { ...(pos ?? position) };
    this.radius = radius;
    this.colour = { ...(color ?? colour) };
    this.intensity = intensity;
    this.flickerSpeed = flickerSpeed;
    this.flickerAmount = flickerAmount;
    this.flickerSeed = flickerSeed ?? boundedLightHash(this.id) * 1000;
    this.enabled = enabled;
  }

  /**
   * Calculates the flicker-adjusted radius for a simulation time.
   *
   * @param {number} timeSeconds Simulation time.
   * @returns {number} Effective radius.
   */
  getEffectiveRadius(timeSeconds) {
    if (!this.enabled || this.flickerAmount <= 0) return this.enabled ? this.radius : 0;
    const wave = Math.sin(timeSeconds * this.flickerSpeed + this.flickerSeed);
    const harmonic = Math.sin(timeSeconds * this.flickerSpeed * 2.17 + this.flickerSeed * 0.71) * 0.35;
    return this.radius * (1 + (wave + harmonic) * this.flickerAmount);
  }

  /**
   * Calculates flicker-adjusted brightness.
   *
   * @param {number} timeSeconds Simulation time.
   * @returns {number} Effective intensity.
   */
  getEffectiveIntensity(timeSeconds) {
    return this.radius === 0 ? 0 : this.intensity * (this.getEffectiveRadius(timeSeconds) / this.radius);
  }

  /**
   * Tests whether this light intersects a world-space viewport.
   *
   * @param {{x: number, y: number, width: number, height: number}} bounds Viewport bounds.
   * @param {number} [timeSeconds=0] Simulation time.
   * @returns {boolean} Whether the light may affect the viewport.
   */
  intersects(bounds, timeSeconds = 0) {
    const radius = this.getEffectiveRadius(timeSeconds);
    return this.enabled
      && this.position.x + radius >= bounds.x
      && this.position.x - radius <= bounds.x + bounds.width
      && this.position.y + radius >= bounds.y
      && this.position.y - radius <= bounds.y + bounds.height;
  }

  /**
   * Produces a renderer-neutral light descriptor.
   *
   * @param {number} timeSeconds Simulation time.
   * @returns {object} Light descriptor.
   */
  describe(timeSeconds = 0) {
    return {
      id: this.id,
      position: { ...this.position },
      radius: this.getEffectiveRadius(timeSeconds),
      colour: { ...this.colour },
      intensity: this.getEffectiveIntensity(timeSeconds),
      enabled: this.enabled,
    };
  }
}

/**
 * Renderer adapter that prepares and composites ambient and point-light passes.
 */
class LightingCompositor {
  /**
   * @param {object} [options] Compositor configuration.
   * @param {AmbientColorGradient} [options.ambientGradient] Ambient palette.
   * @param {object|null} [options.ambientOverride] Optional fixed ambient colour.
   */
  constructor({ ambientGradient = new AmbientColorGradient(), ambientOverride = null } = {}) {
    this.ambientGradient = ambientGradient;
    this.ambientOverride = ambientOverride;
    this.lights = new Map();
  }

  /** @param {import('./LightSource.js').LightSource} light Light to register. */
  addLight(light) { this.lights.set(light.id, light); return light; }
  /** @param {string} id Light identifier. @returns {boolean} Removal result. */
  removeLight(id) { return this.lights.delete(id); }
  /** Removes every light. */
  clearLights() { this.lights.clear(); }

  /**
   * Builds a renderer-neutral frame, culling off-screen lights before rendering.
   *
   * @param {number} normalisedTime Celestial time.
   * @param {{x: number, y: number, width: number, height: number}} bounds Viewport bounds.
   * @param {number} [timeSeconds=0] Simulation time.
   * @returns {{ambient: object, lights: object[]}} Lighting frame.
   */
  createFrame(normalisedTime, bounds, timeSeconds = 0) {
    const ambient = this.ambientOverride ? { ...this.ambientOverride } : this.ambientGradient.evaluate(normalisedTime);
    const lights = [...this.lights.values()]
      .filter((light) => light.intersects(bounds, timeSeconds))
      .map((light) => light.describe(timeSeconds));
    return { ambient, lights };
  }

  /**
   * Draws a prepared lighting frame through a Canvas 2D-compatible renderer.
   * The simulation state stays headless; this method is an opt-in adapter.
   *
   * @param {CanvasRenderingContext2D} context Canvas context.
   * @param {{ambient: object, lights: object[]}} frame Prepared lighting frame.
   * @param {{x: number, y: number, width: number, height: number}} bounds Viewport bounds.
   */
  compositeCanvas(context, frame, bounds) {
    const { r, g, b, a } = frame.ambient;
    context.save();
    context.globalCompositeOperation = 'multiply';
    context.fillStyle = `rgba(${r}, ${g}, ${b}, ${a})`;
    context.fillRect(0, 0, bounds.width, bounds.height);
    context.globalCompositeOperation = 'lighter';
    for (const light of frame.lights) {
      const x = light.position.x - bounds.x;
      const y = light.position.y - bounds.y;
      const gradient = context.createRadialGradient(x, y, 0, x, y, light.radius);
      const colour = light.colour;
      gradient.addColorStop(0, `rgba(${colour.r}, ${colour.g}, ${colour.b}, ${light.intensity})`);
      gradient.addColorStop(0.7, `rgba(${colour.r}, ${colour.g}, ${colour.b}, ${light.intensity * 0.3})`);
      gradient.addColorStop(1, `rgba(${colour.r}, ${colour.g}, ${colour.b}, 0)`);
      context.fillStyle = gradient;
      context.beginPath();
      context.arc(x, y, light.radius, 0, Math.PI * 2);
      context.fill();
    }
    context.restore();
  }
}

const climateClamp = (value, low, high) => Math.max(low, Math.min(high, value));

/**
 * Immutable catalogue of weather-driven climate and gameplay modifiers.
 */
class ClimateMatrix {
  /**
   * @param {Record<string, object>} [presets] Named climate presets.
   */
  constructor(presets = ClimateMatrix.defaultPresets()) {
    this.presets = new Map();
    for (const [key, preset] of Object.entries(presets)) this.set(key, preset);
  }

  /**
   * Stores a normalised preset.
   *
   * @param {string} key Weather identifier.
   * @param {object} preset Climate values.
   */
  set(key, preset) {
    this.presets.set(key, ClimateMatrix.normalisePreset(key, preset));
  }

  /**
   * Gets a cloned climate preset.
   *
   * @param {string} key Weather identifier.
   * @returns {object} Climate values.
   */
  get(key) {
    const preset = this.presets.get(key);
    if (!preset) throw new RangeError(`Unknown weather preset: ${key}.`);
    return ClimateMatrix.clonePreset(preset);
  }

  /**
   * Linearly blends two named weather presets.
   *
   * @param {string} fromKey Initial weather identifier.
   * @param {string} toKey Target weather identifier.
   * @param {number} progress Transition amount from zero to one.
   * @returns {object} Blended climate values.
   */
  blend(fromKey, toKey, progress) {
    return ClimateMatrix.blendPresets(this.get(fromKey), this.get(toKey), progress);
  }

  /** @returns {Record<string, object>} Built-in climate presets. */
  static defaultPresets() {
    return {
      clear: { visibility: 1, temperatureOffset: 0, wind: { x: 40, y: 0 }, wetnessRate: 0, particleKind: null },
      rain: { visibility: 0.65, temperatureOffset: -6, wind: { x: 150, y: 500 }, wetnessRate: 0.05, particleKind: 'rain', elementalModifiers: { lightning: 0.3 } },
      blizzard: { visibility: 0.3, temperatureOffset: -18, wind: { x: -300, y: 350 }, wetnessRate: -0.02, particleKind: 'snow', movementMultiplier: 0.75 },
      heatwave: { visibility: 0.75, temperatureOffset: 15, wind: { x: 20, y: 0 }, wetnessRate: -0.1, particleKind: 'ash', staminaDrainMultiplier: 1.4, elementalModifiers: { fire: 0.2 } },
      ash: { visibility: 0.7, temperatureOffset: 8, wind: { x: 80, y: 130 }, wetnessRate: -0.04, particleKind: 'ash' },
      miasma: { visibility: 0.5, temperatureOffset: -2, wind: { x: 0, y: 0 }, wetnessRate: 0, particleKind: 'fog', toxic: true },
    };
  }

  /** @param {string} key @param {object} preset @returns {object} Normalised preset. */
  static normalisePreset(key, preset) {
    return {
      key,
      visibility: climateClamp(Number(preset.visibility ?? 1), 0, 1),
      temperatureOffset: Number(preset.temperatureOffset ?? 0),
      wind: { x: Number(preset.wind?.x ?? 0), y: Number(preset.wind?.y ?? 0) },
      wetnessRate: Number(preset.wetnessRate ?? 0),
      particleKind: preset.particleKind ?? null,
      movementMultiplier: Number(preset.movementMultiplier ?? 1),
      staminaDrainMultiplier: Number(preset.staminaDrainMultiplier ?? 1),
      elementalModifiers: { ...(preset.elementalModifiers ?? {}) },
      toxic: Boolean(preset.toxic),
    };
  }

  /** @param {object} preset @returns {object} Cloned preset. */
  static clonePreset(preset) {
    return { ...preset, wind: { ...preset.wind }, elementalModifiers: { ...preset.elementalModifiers } };
  }

  /** @param {object} from @param {object} to @param {number} amount @returns {object} Blended preset. */
  static blendPresets(from, to, amount) {
    const progress = climateClamp(amount, 0, 1);
    const blendValue = (first, second) => first + (second - first) * progress;
    const keys = new Set([...Object.keys(from.elementalModifiers ?? {}), ...Object.keys(to.elementalModifiers ?? {})]);
    const elementalModifiers = {};
    for (const key of keys) elementalModifiers[key] = blendValue(from.elementalModifiers?.[key] ?? 0, to.elementalModifiers?.[key] ?? 0);
    return {
      key: progress >= 1 ? to.key : from.key,
      visibility: blendValue(from.visibility, to.visibility),
      temperatureOffset: blendValue(from.temperatureOffset, to.temperatureOffset),
      wind: { x: blendValue(from.wind.x, to.wind.x), y: blendValue(from.wind.y, to.wind.y) },
      wetnessRate: blendValue(from.wetnessRate, to.wetnessRate),
      particleKind: progress < 0.5 ? from.particleKind : to.particleKind,
      movementMultiplier: blendValue(from.movementMultiplier, to.movementMultiplier),
      staminaDrainMultiplier: blendValue(from.staminaDrainMultiplier, to.staminaDrainMultiplier),
      elementalModifiers,
      toxic: progress < 0.5 ? from.toxic : to.toxic,
    };
  }
}

/**
 * A renderer-neutral weather particle constrained to the active viewport.
 */
class PrecipitationParticle {
  /**
   * @param {object} values Particle values.
   */
  constructor({ x = 0, y = 0, length = 8, speed = 1, drift = 0 } = {}) {
    this.x = x;
    this.y = y;
    this.length = length;
    this.speed = speed;
    this.drift = drift;
  }

  /**
   * Advances and recycles the particle inside viewport bounds.
   *
   * @param {number} deltaSeconds Simulation delta.
   * @param {{x: number, y: number}} wind World wind.
   * @param {{x: number, y: number, width: number, height: number}} bounds Viewport bounds.
   */
  update(deltaSeconds, wind, bounds) {
    this.x += (wind.x * this.speed + this.drift) * deltaSeconds;
    this.y += wind.y * this.speed * deltaSeconds;
    this.x = PrecipitationParticle.wrap(this.x, bounds.x, bounds.width);
    this.y = PrecipitationParticle.wrap(this.y, bounds.y, bounds.height);
  }

  /** @returns {object} Plain particle data. */
  serialise() { return { x: this.x, y: this.y, length: this.length, speed: this.speed, drift: this.drift }; }

  /**
   * Wraps a coordinate across a finite viewport span, including long-frame travel.
   *
   * @param {number} value Coordinate to wrap.
   * @param {number} origin Lower span boundary.
   * @param {number} span Positive span width.
   * @returns {number} Wrapped coordinate.
   */
  static wrap(value, origin, span) {
    if (!Number.isFinite(span) || span <= 0) return origin;
    return origin + (((value - origin) % span) + span) % span;
  }
}

const weatherClamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));
const seededWeatherRandom = (seed) => {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6D2B79F5) >>> 0;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
};

/**
 * Deterministic weather state, climate transitions, and viewport-bounded particles.
 */
class WeatherSystem {
  /**
   * @param {object} [options] Weather configuration.
   */
  constructor({
    climateMatrix = new ClimateMatrix(),
    initialWeather = 'clear',
    maxParticles = 240,
    randomSeed = 0xC0FFEE,
    eventBus,
  } = {}) {
    if (!Number.isInteger(maxParticles) || maxParticles < 0) {
      throw new RangeError('Maximum weather particles must be a non-negative integer.');
    }
    this.climateMatrix = climateMatrix;
    this.currentWeather = initialWeather;
    this.targetWeather = initialWeather;
    this.transitionDuration = 0;
    this.transitionProgress = 1;
    this.maxParticles = maxParticles;
    this.particles = [];
    this.eventBus = eventBus ?? new EnvironmentEventBus();
    this.random = seededWeatherRandom(randomSeed);
    this.climate = this.climateMatrix.get(initialWeather);
  }

  /** @returns {number} Current environmental temperature adjustment. */
  get temperatureOffset() { return this.climate.temperatureOffset; }
  /** @returns {number} Current visibility factor. */
  get visibilityFactor() { return this.climate.visibility; }
  /** @returns {{x: number, y: number}} Current wind vector. */
  get wind() { return { ...this.climate.wind }; }

  /**
   * Starts a smooth transition to a known weather preset.
   *
   * @param {string} weatherKey Target weather key.
   * @param {number} [transitionDuration=5] Transition duration in seconds.
   */
  setWeather(weatherKey, transitionDuration = 5) {
    this.climateMatrix.get(weatherKey);
    if (!Number.isFinite(transitionDuration) || transitionDuration < 0) {
      throw new RangeError('Weather transition duration must be non-negative.');
    }
    if (weatherKey === this.targetWeather && this.transitionProgress < 1) return;
    this.currentWeather = this.transitionProgress < 1 ? this.currentWeather : this.targetWeather;
    this.targetWeather = weatherKey;
    this.transitionDuration = transitionDuration;
    this.transitionProgress = transitionDuration === 0 ? 1 : 0;
    if (this.transitionProgress === 1) {
      this.currentWeather = weatherKey;
      this.climate = this.climateMatrix.get(weatherKey);
      this.eventBus.emit(EnvironmentEvents.WEATHER_CHANGE, this.snapshot());
    }
  }

  /**
   * Selects a weather key from positive biome weights using the seeded generator.
   *
   * @param {Record<string, number>} weights Weather probability weights.
   * @param {number} [transitionDuration=5] Transition duration.
   * @returns {string} Selected weather key.
   */
  chooseWeather(weights, transitionDuration = 5) {
    const entries = Object.entries(weights).filter(([, weight]) => Number.isFinite(weight) && weight > 0);
    const total = entries.reduce((sum, [, weight]) => sum + weight, 0);
    if (total <= 0) throw new RangeError('Weather weights must contain a positive value.');
    let point = this.random() * total;
    let selected = entries[entries.length - 1][0];
    for (const [key, weight] of entries) {
      point -= weight;
      if (point <= 0) { selected = key; break; }
    }
    this.setWeather(selected, transitionDuration);
    return selected;
  }

  /**
   * Advances climate blending and particles. Bounds are required only for particle simulation.
   *
   * @param {number} deltaSeconds Simulation delta.
   * @param {{x: number, y: number, width: number, height: number}} [bounds] Active camera bounds.
   * @returns {object} Weather snapshot.
   */
  update(deltaSeconds, bounds) {
    if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) {
      throw new RangeError('Weather delta seconds must be finite and non-negative.');
    }
    const previousProgress = this.transitionProgress;
    if (this.transitionProgress < 1) {
      this.transitionProgress = weatherClamp(
        this.transitionProgress + deltaSeconds / Math.max(this.transitionDuration, Number.EPSILON), 0, 1,
      );
      this.climate = this.climateMatrix.blend(this.currentWeather, this.targetWeather, this.transitionProgress);
      this.eventBus.emit(EnvironmentEvents.WEATHER_TRANSITION, this.snapshot());
      if (this.transitionProgress === 1 && previousProgress < 1) {
        this.currentWeather = this.targetWeather;
        this.climate = this.climateMatrix.get(this.currentWeather);
        this.eventBus.emit(EnvironmentEvents.WEATHER_CHANGE, this.snapshot());
      }
    }
    if (bounds) this.updateParticles(deltaSeconds, bounds);
    return this.snapshot();
  }

  /**
   * Updates particles exclusively inside camera bounds.
   *
   * @param {number} deltaSeconds Simulation delta.
   * @param {{x: number, y: number, width: number, height: number}} bounds Active bounds.
   */
  updateParticles(deltaSeconds, bounds) {
    const particleKind = this.climate.particleKind;
    if (!particleKind || this.maxParticles === 0) {
      this.particles.length = 0;
      return;
    }
    const density = particleKind === 'fog' ? 0.35 : 1;
    const desired = Math.round(this.maxParticles * density);
    while (this.particles.length < desired) this.particles.push(this.createParticle(bounds, particleKind));
    if (this.particles.length > desired) this.particles.length = desired;
    for (const particle of this.particles) particle.update(deltaSeconds, this.climate.wind, bounds);
  }

  /**
   * Creates one seeded particle inside the viewport.
   *
   * @param {{x: number, y: number, width: number, height: number}} bounds Active bounds.
   * @param {string} kind Visual particle kind.
   * @returns {PrecipitationParticle} Particle.
   */
  createParticle(bounds, kind) {
    const snow = kind === 'snow';
    const fog = kind === 'fog';
    return new PrecipitationParticle({
      x: bounds.x + this.random() * bounds.width,
      y: bounds.y + this.random() * bounds.height,
      length: fog ? 28 + this.random() * 30 : snow ? 3 + this.random() * 3 : 10 + this.random() * 12,
      speed: fog ? 0.12 + this.random() * 0.15 : 0.7 + this.random() * 0.6,
      drift: snow ? (this.random() - 0.5) * 30 : 0,
    });
  }

  /** @returns {object} Renderer-neutral current weather state. */
  snapshot() {
    return {
      currentWeather: this.currentWeather,
      targetWeather: this.targetWeather,
      transitionProgress: this.transitionProgress,
      transitionDuration: this.transitionDuration,
      climate: ClimateMatrix.clonePreset(this.climate),
      particleCount: this.particles.length,
    };
  }

  /** @returns {object} Persistable weather state. */
  serialise() {
    return { ...this.snapshot(), particles: this.particles.map((particle) => particle.serialise()) };
  }
}

/**
 * Headless radial source of environmental heat.
 */
class HeatSource {
  /**
   * @param {object} [options] Heat source configuration.
   */
  constructor({ id = 'heat-source', x = 0, y = 0, radius = 100, heatOutput = 10, falloff = 1 } = {}) {
    if (!Number.isFinite(radius) || radius <= 0) {
      throw new RangeError('Heat source radius must be greater than zero.');
    }
    this.id = String(id);
    this.x = x;
    this.y = y;
    this.radius = radius;
    this.heatOutput = heatOutput;
    this.falloff = Math.max(0.01, falloff);
  }

  /**
   * Calculates radiant heat at a world position.
   *
   * @param {{x: number, y: number}} position Recipient world position.
   * @returns {number} Temperature contribution in degrees Celsius.
   */
  getContribution(position) {
    const distance = Math.hypot(this.x - position.x, this.y - position.y);
    if (distance >= this.radius) return 0;
    return this.heatOutput * (1 - distance / this.radius) ** this.falloff;
  }

  /** @returns {object} Persistable source description. */
  serialise() {
    return {
      id: this.id,
      x: this.x,
      y: this.y,
      radius: this.radius,
      heatOutput: this.heatOutput,
      falloff: this.falloff,
    };
  }
}

/**
 * Pure heat-conduction model used by survival systems.
 */
class ThermodynamicModel {
  /**
   * @param {object} [options] Thermodynamic constants.
   * @param {number} [options.thermalConstant=8] Baseline thermal inertia.
   * @param {number} [options.exchangeRate=0.02] Heat exchange rate per second.
   */
  constructor({ thermalConstant = 8, exchangeRate = 0.02 } = {}) {
    if (!Number.isFinite(thermalConstant) || thermalConstant <= 0) {
      throw new RangeError('Thermal constant must be greater than zero.');
    }
    if (!Number.isFinite(exchangeRate) || exchangeRate < 0) {
      throw new RangeError('Heat exchange rate must be non-negative.');
    }
    this.thermalConstant = thermalConstant;
    this.exchangeRate = exchangeRate;
  }

  /**
   * Applies the required heat-balance equation over a continuous delta.
   *
   * dT/dt = (environment - body) / (insulation + thermalConstant) * exchangeRate
   *
   * @param {number} bodyTemperature Current core temperature.
   * @param {number} environmentTemperature Effective environmental temperature.
   * @param {number} insulation Clothing insulation.
   * @param {number} deltaSeconds Simulation delta.
   * @returns {{temperature: number, delta: number, rate: number}} Integrated result.
   */
  step(bodyTemperature, environmentTemperature, insulation, deltaSeconds) {
    if (![bodyTemperature, environmentTemperature, insulation, deltaSeconds].every(Number.isFinite)) {
      throw new TypeError('Thermodynamic values must be finite.');
    }
    if (deltaSeconds < 0) throw new RangeError('Thermodynamic delta must be non-negative.');
    const thermalResistance = Math.max(0, insulation) + this.thermalConstant;
    const delta = environmentTemperature - bodyTemperature;
    const rate = (delta / thermalResistance) * this.exchangeRate;
    return { temperature: bodyTemperature + rate * deltaSeconds, delta, rate };
  }

  /**
   * Totals radiant heat from compatible heat-source objects.
   *
   * @param {{x: number, y: number}} position Recipient world position.
   * @param {Array<object>} sources Nearby heat sources.
   * @returns {number} Total heat contribution.
   */
  calculateRadiantHeat(position, sources) {
    return sources.reduce((total, source) => {
      if (typeof source.getContribution === 'function') return total + source.getContribution(position);
      const distance = Math.hypot((source.x ?? 0) - position.x, (source.y ?? 0) - position.y);
      if (!Number.isFinite(source.radius) || distance >= source.radius) return total;
      const falloff = Math.max(0.01, source.falloff ?? 1);
      return total + (source.heatOutput ?? 0) * (1 - distance / source.radius) ** falloff;
    }, 0);
  }
}

const vitalClamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));

/**
 * Headless physiological survival simulation for one character.
 */
class SurvivalVitalManager {
  /**
   * @param {object} [options] Vital configuration.
   */
  constructor({
    targetCharacter,
    baseWarmth = 37,
    hunger = 100,
    thirst = 100,
    stamina = 100,
    oxygen = 100,
    thermodynamicModel = new ThermodynamicModel(),
    hungerDrainPerSecond = 0.12,
    thirstDrainPerSecond = 0.2,
    oxygenDrainPerSecond = 12,
    oxygenRecoveryPerSecond = 25,
    drowningDamagePerSecond = 15,
  } = {}) {
    this.character = targetCharacter ?? null;
    this.bodyTemperature = baseWarmth;
    this.hunger = vitalClamp(hunger, 0, 100);
    this.thirst = vitalClamp(thirst, 0, 100);
    this.stamina = vitalClamp(stamina, 0, 100);
    this.oxygen = vitalClamp(oxygen, 0, 100);
    this.isSubmerged = false;
    this.isSprinting = false;
    this.thermodynamicModel = thermodynamicModel;
    this.hungerDrainPerSecond = hungerDrainPerSecond;
    this.thirstDrainPerSecond = thirstDrainPerSecond;
    this.oxygenDrainPerSecond = oxygenDrainPerSecond;
    this.oxygenRecoveryPerSecond = oxygenRecoveryPerSecond;
    this.drowningDamagePerSecond = drowningDamagePerSecond;
    this.conditions = new Set();
  }

  /** @returns {number} Compatibility alias for core body temperature. */
  get bodyTemp() { return this.bodyTemperature; }
  /** @param {number} value Core temperature. */
  set bodyTemp(value) { this.bodyTemperature = value; }

  /**
   * Advances thermal and vital state without DOM or renderer dependencies.
   *
   * @param {number} deltaSeconds Simulation delta.
   * @param {object} [environment] Environmental inputs.
   * @param {Array<object>} [heatSources] Nearby radiant heat sources.
   * @returns {object} Current vital snapshot.
   */
  update(deltaSeconds, environment = {}, heatSources = []) {
    if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) {
      throw new RangeError('Vital delta seconds must be finite and non-negative.');
    }
    if (this.character?.isDead) return this.snapshot();
    const position = { x: this.character?.x ?? 0, y: this.character?.y ?? 0 };
    const ambientTemperature = Number(environment.ambientTemperature ?? 20);
    const weatherOffset = Number(environment.weatherTempOffset ?? environment.temperatureOffset ?? 0);
    const wetnessPenalty = environment.isRaining || environment.wet ? -5 : 0;
    const radiantHeat = this.thermodynamicModel.calculateRadiantHeat(position, heatSources);
    const effectiveTemperature = ambientTemperature + weatherOffset + wetnessPenalty + radiantHeat;
    const insulation = this.getCharacterAttribute('insulation', 0);
    this.bodyTemperature = this.thermodynamicModel.step(
      this.bodyTemperature, effectiveTemperature, insulation, deltaSeconds,
    ).temperature;

    const shivering = this.bodyTemperature < 35.5;
    const sweating = this.bodyTemperature > 38;
    const sprintMultiplier = this.isSprinting || environment.isSprinting ? 1.35 : 1;
    const climateStaminaMultiplier = Number(environment.staminaDrainMultiplier ?? 1);
    this.hunger = vitalClamp(
      this.hunger - this.hungerDrainPerSecond * (shivering ? 1.6 : 1) * sprintMultiplier * deltaSeconds, 0, 100,
    );
    this.thirst = vitalClamp(
      this.thirst - this.thirstDrainPerSecond * (sweating ? 1.8 : 1) * sprintMultiplier * deltaSeconds, 0, 100,
    );
    this.updateStamina(deltaSeconds, { shivering, climateStaminaMultiplier, resting: environment.resting });
    this.updateOxygen(deltaSeconds);
    this.evaluateConditions();
    return this.snapshot();
  }

  /**
   * Sets water submersion state.
   *
   * @param {boolean} submerged Whether the character is submerged.
   */
  setSubmerged(submerged) { this.isSubmerged = Boolean(submerged); }

  /**
   * Sets sprinting state.
   *
   * @param {boolean} sprinting Whether the character is sprinting.
   */
  setSprinting(sprinting) { this.isSprinting = Boolean(sprinting); }

  /**
   * Restores a bounded vitality pool.
   *
   * @param {'hunger'|'thirst'|'stamina'|'oxygen'} pool Pool name.
   * @param {number} amount Positive restoration amount.
   */
  restore(pool, amount) {
    if (!['hunger', 'thirst', 'stamina', 'oxygen'].includes(pool)) {
      throw new RangeError(`Unknown vitality pool: ${pool}.`);
    }
    if (!Number.isFinite(amount) || amount < 0) throw new RangeError('Restoration amount must be non-negative.');
    this[pool] = vitalClamp(this[pool] + amount, 0, 100);
  }

  /**
   * Gets an effective numeric attribute from the target character.
   *
   * @param {string} name Attribute name.
   * @param {number} fallback Fallback value.
   * @returns {number} Effective attribute.
   */
  getCharacterAttribute(name, fallback) {
    const attribute = this.character?.getAttribute?.(name);
    return Number(attribute?.value ?? fallback);
  }

  /**
   * Applies stamina depletion or recovery.
   *
   * @param {number} deltaSeconds Simulation delta.
   * @param {object} state Current physiological state.
   */
  updateStamina(deltaSeconds, { shivering, climateStaminaMultiplier, resting }) {
    if (this.isSprinting) {
      this.stamina = vitalClamp(this.stamina - 8 * climateStaminaMultiplier * deltaSeconds, 0, 100);
      return;
    }
    const recovery = (resting ? 12 : 6) * (shivering ? 0.6 : 1) * (this.hunger === 0 || this.thirst === 0 ? 0.4 : 1);
    this.stamina = vitalClamp(this.stamina + recovery * deltaSeconds, 0, 100);
  }

  /**
   * Updates oxygen and issues deterministic true drowning damage.
   *
   * @param {number} deltaSeconds Simulation delta.
   */
  updateOxygen(deltaSeconds) {
    if (this.isSubmerged) {
      this.oxygen = vitalClamp(this.oxygen - this.oxygenDrainPerSecond * deltaSeconds, 0, 100);
      if (this.oxygen === 0 && this.drowningDamagePerSecond > 0) {
        this.character?.takeDamage?.({
          rawAmount: this.drowningDamagePerSecond * deltaSeconds,
          type: 'true',
          isTrueDamage: true,
          canCrit: false,
        });
      }
    } else {
      this.oxygen = vitalClamp(this.oxygen + this.oxygenRecoveryPerSecond * deltaSeconds, 0, 100);
    }
  }

  /**
   * Reconciles active physiological conditions with current thresholds.
   */
  evaluateConditions() {
    this.reconcileCondition('hypothermia_severe', this.bodyTemperature < 34.5);
    this.reconcileCondition('hypothermia_mild', this.bodyTemperature >= 34.5 && this.bodyTemperature < 35.5);
    this.reconcileCondition('hyperthermia_severe', this.bodyTemperature > 40);
    this.reconcileCondition('hyperthermia_mild', this.bodyTemperature > 39 && this.bodyTemperature <= 40);
    this.reconcileCondition('starvation_dying', this.hunger === 0);
    this.reconcileCondition('dehydration_dying', this.thirst === 0);
  }

  /**
   * Adds or removes a threshold condition exactly once per state change.
   *
   * @param {string} id Condition identifier.
   * @param {boolean} active Whether it should be active.
   */
  reconcileCondition(id, active) {
    const currentlyActive = this.conditions.has(id);
    if (active === currentlyActive) return;
    if (active) {
      this.conditions.add(id);
      this.character?.applyStatusEffect?.(id);
    } else {
      this.conditions.delete(id);
      this.character?.removeStatusEffect?.(id);
    }
    this.character?.emit?.(EnvironmentEvents.VITAL_THRESHOLD, { id, active, vitals: this.snapshot() });
  }

  /** @returns {object} Persistable vital state. */
  snapshot() {
    return {
      bodyTemperature: this.bodyTemperature,
      hunger: this.hunger,
      thirst: this.thirst,
      stamina: this.stamina,
      oxygen: this.oxygen,
      isSubmerged: this.isSubmerged,
      isSprinting: this.isSprinting,
      conditions: [...this.conditions],
    };
  }

  /** @returns {object} Persistable vital state. */
  serialise() { return this.snapshot(); }

  /**
   * Restores a manager state around a target character.
   *
   * @param {object} state Saved vitality state.
   * @param {object} options Additional constructor options.
   * @returns {SurvivalVitalManager} Restored manager.
   */
  static deserialise(state, options = {}) {
    const manager = new SurvivalVitalManager({ ...options, baseWarmth: state.bodyTemperature, ...state });
    manager.conditions = new Set(state.conditions ?? []);
    return manager;
  }
}

/**
 * Modifier operation types applied by an Attribute.
 *
 * @readonly
 */
const ModifierType = Object.freeze({
  FLAT: 0,
  PERCENT_ADDITIVE: 1,
  PERCENT_MULTIPLICATIVE: 2,
});

/**
 * Immutable description of one layered attribute modifier.
 */
class StatModifier {
  /**
   * @param {object} options Modifier values.
   * @param {string} options.id Unique modifier identifier.
   * @param {string} options.type Modifier operation type.
   * @param {number} options.value Modifier magnitude.
   * @param {string} [options.source='generic'] Owning system identifier.
   */
  constructor({ id, type = ModifierType.FLAT, value = 0, source = 'generic' } = {}) {
    if (!id) throw new TypeError('A stat modifier requires an identifier.');
    if (!Object.values(ModifierType).includes(type)) throw new RangeError(`Unknown modifier type: ${type}.`);
    if (!Number.isFinite(value)) throw new TypeError('A stat modifier value must be finite.');
    this.id = String(id);
    this.type = type;
    this.value = value;
    this.source = String(source);
    Object.freeze(this);
  }

  /** @returns {object} Plain serialisable modifier data. */
  serialise() { return { id: this.id, type: this.type, value: this.value, source: this.source }; }
}

const attributeClamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));

/**
 * A dirty-cached layered numeric attribute.
 */
class Attribute {
  /**
   * @param {object} options Attribute configuration.
   * @param {string} options.name Attribute name.
   * @param {number} [options.base=0] Unmodified base value.
   * @param {number} [options.min=-Infinity] Effective lower bound.
   * @param {number} [options.max=Infinity] Effective upper bound.
   */
  constructor({ name, base = 0, min = -Infinity, max = Infinity } = {}) {
    if (!name) throw new TypeError('An attribute requires a name.');
    if (!Number.isFinite(base) || (!Number.isFinite(min) && min !== -Infinity)
      || (!Number.isFinite(max) && max !== Infinity)) {
      throw new TypeError('Attribute bounds and base must be numeric.');
    }
    if (min > max) throw new RangeError('Attribute minimum cannot exceed maximum.');
    this.name = String(name);
    this.base = base;
    this.min = min;
    this.max = max;
    this.modifiers = new Map();
    this.cachedValue = base;
    this.isDirty = true;
    this.recalculationCount = 0;
  }

  /** @returns {number} Current effective value, recalculated only when dirty. */
  get value() {
    if (this.isDirty) this.recalculate();
    return this.cachedValue;
  }

  /**
   * Updates the unmodified value and invalidates the cache.
   *
   * @param {number} value New base value.
   * @returns {Attribute} This attribute.
   */
  setBase(value) {
    if (!Number.isFinite(value)) throw new TypeError('Attribute base must be finite.');
    if (this.base !== value) {
      this.base = value;
      this.isDirty = true;
    }
    return this;
  }

  /**
   * Adds or replaces one modifier.
   *
   * @param {StatModifier|string} modifier Modifier instance or identifier.
   * @param {string} [type] Modifier type when using the shorthand form.
   * @param {number} [value] Modifier value when using the shorthand form.
   * @param {string} [source='generic'] Modifier source when using the shorthand form.
   * @returns {Attribute} This attribute.
   */
  addModifier(modifier, type, value, source = 'generic') {
    const resolved = modifier instanceof StatModifier
      ? modifier
      : new StatModifier({ id: modifier, type, value, source });
    this.modifiers.set(resolved.id, resolved);
    this.isDirty = true;
    return this;
  }

  /**
   * Removes a modifier by identifier.
   *
   * @param {string} id Modifier identifier.
   * @returns {boolean} Whether a modifier was removed.
   */
  removeModifier(id) {
    const removed = this.modifiers.delete(id);
    if (removed) this.isDirty = true;
    return removed;
  }

  /**
   * Removes every modifier belonging to a source.
   *
   * @param {string} source Modifier source.
   * @returns {number} Number of removed modifiers.
   */
  removeModifiersBySource(source) {
    let removed = 0;
    for (const [id, modifier] of this.modifiers) {
      if (modifier.source === source) {
        this.modifiers.delete(id);
        removed += 1;
      }
    }
    if (removed > 0) this.isDirty = true;
    return removed;
  }

  /**
   * Explicitly marks the cached value stale.
   */
  invalidate() { this.isDirty = true; }

  /**
   * Evaluates the required deterministic modifier precedence formula.
   *
   * @returns {number} New effective value.
   */
  recalculate() {
    let flatSum = 0;
    let additiveSum = 0;
    let multiplicativeProduct = 1;
    for (const modifier of this.modifiers.values()) {
      if (modifier.type === ModifierType.FLAT) flatSum += modifier.value;
      else if (modifier.type === ModifierType.PERCENT_ADDITIVE) additiveSum += modifier.value;
      else multiplicativeProduct *= 1 + modifier.value;
    }
    this.cachedValue = attributeClamp(
      ((this.base + flatSum) * (1 + additiveSum)) * multiplicativeProduct,
      this.min,
      this.max,
    );
    this.isDirty = false;
    this.recalculationCount += 1;
    return this.cachedValue;
  }

  /** @returns {object} Persistable attribute state. */
  serialise() {
    return {
      name: this.name,
      base: this.base,
      min: this.min,
      max: this.max,
      modifiers: [...this.modifiers.values()].map((modifier) => modifier.serialise()),
    };
  }

  /**
   * Restores an attribute from state.
   *
   * @param {object} state Attribute state.
   * @returns {Attribute} Restored attribute.
   */
  static deserialise(state) {
    const attribute = new Attribute(state);
    for (const modifier of state.modifiers ?? []) attribute.addModifier(new StatModifier(modifier));
    return attribute;
  }
}

/**
 * Immutable input to the combat damage pipeline.
 */
class DamagePayload {
  /**
   * @param {object} [options] Damage values.
   */
  constructor({
    rawAmount = 0,
    type = 'physical',
    attacker = null,
    canCrit = true,
    isTrueDamage = false,
    tags = [],
    random = null,
    metadata = {},
  } = {}) {
    if (!Number.isFinite(rawAmount)) throw new TypeError('Damage amount must be finite.');
    this.rawAmount = Math.max(0, rawAmount);
    this.type = String(type);
    this.attacker = attacker;
    this.canCrit = Boolean(canCrit);
    this.isTrueDamage = Boolean(isTrueDamage) || this.type === 'true';
    this.tags = [...tags];
    this.random = random;
    this.metadata = { ...metadata };
    Object.freeze(this.tags);
    Object.freeze(this.metadata);
    Object.freeze(this);
  }

  /**
   * Converts plain input into a payload instance.
   *
   * @param {DamagePayload|object} payload Damage input.
   * @returns {DamagePayload} Payload instance.
   */
  static from(payload) { return payload instanceof DamagePayload ? payload : new DamagePayload(payload); }
}

const combatClamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));
const findAttribute = (target, names) => {
  for (const name of names) {
    const attribute = target?.getAttribute?.(name);
    if (attribute) return attribute;
  }
  return null;
};

/**
 * Five-stage deterministic combat damage resolver.
 */
class CombatResolver {
  /**
   * Resolves one payload against a target.
   *
   * @param {object} target Target exposing `getAttribute` and optional shields.
   * @param {DamagePayload|object} input Damage input.
   * @param {object} [options] Resolution options.
   * @param {number} [options.defenceConstant=100] Diminishing-return defence constant.
   * @param {() => number} [options.random] Deterministic random provider for critical checks.
   * @returns {object} Detailed combat receipt.
   */
  static resolveDamage(target, input, options = {}) {
    if (!target) throw new TypeError('Combat resolution requires a target.');
    const settings = Number.isFinite(options) ? { defenceConstant: options } : options;
    const defenceConstant = settings.defenceConstant ?? settings.defenseK ?? 100;
    const { random } = settings;
    if (!Number.isFinite(defenceConstant) || defenceConstant <= 0) {
      throw new RangeError('Defence constant must be greater than zero.');
    }
    const payload = DamagePayload.from(input);
    let amount = payload.rawAmount;
    const originalAmount = amount;
    const randomValue = (random ?? payload.random ?? (() => 1))();
    let isCrit = false;
    let mitigation = 0;

    if (payload.canCrit && payload.attacker && !payload.isTrueDamage) {
      const chance = combatClamp(Number(findAttribute(payload.attacker, ['critChance', 'criticalChance'])?.value ?? 0), 0, 1);
      if (randomValue < chance) {
        isCrit = true;
        const multiplier = Math.max(0, Number(findAttribute(payload.attacker, ['critDamage', 'criticalDamage'])?.value ?? 1.5));
        amount *= multiplier;
      }
    }

    const preMitigationAmount = amount;
    if (!payload.isTrueDamage) {
      if (payload.type === 'physical') {
        const armour = Math.max(0, Number(findAttribute(target, ['armour', 'armor', 'defence', 'defense'])?.value ?? 0));
        mitigation = armour / (armour + defenceConstant);
      } else {
        const resistance = Number(findAttribute(target, [
          `res_${payload.type}`,
          `resistance_${payload.type}`,
          `${payload.type}Resistance`,
        ])?.value ?? 0);
        mitigation = combatClamp(resistance, -1, 0.85);
      }
      amount *= 1 - mitigation;
    }
    amount = Math.max(0, amount);

    let absorbedDamage = 0;
    const shields = Array.isArray(target.shields) ? target.shields : [];
    for (let index = shields.length - 1; index >= 0 && amount > 0; index -= 1) {
      const shield = shields[index];
      const available = Math.max(0, Number(shield.amount ?? 0));
      const absorbed = Math.min(available, amount);
      shield.amount = available - absorbed;
      amount -= absorbed;
      absorbedDamage += absorbed;
      if (shield.amount <= 0) shields.splice(index, 1);
    }

    const appliedDamage = Math.max(0, amount);
    const health = findAttribute(target, ['health', 'hp']);
    if (health) health.setBase(Math.max(0, health.base - appliedDamage));
    const receipt = {
      originalAmount,
      criticalAmount: preMitigationAmount,
      mitigation,
      mitigatedDamage: Math.max(0, preMitigationAmount - appliedDamage - absorbedDamage),
      absorbedDamage,
      appliedDamage,
      isCrit,
      isTrueDamage: payload.isTrueDamage,
      damageType: payload.type,
      isDead: health ? health.base <= 0 : Boolean(target.isDead),
      target,
      attacker: payload.attacker,
      payload,
    };
    target.emit?.(EnvironmentEvents.DAMAGE_RESOLVED, receipt);
    target.emit?.('onDamageTaken', receipt);
    payload.attacker?.emit?.('onDamageDealt', receipt);
    return receipt;
  }
}

/**
 * Reapplication behaviours for active status effects.
 *
 * @readonly
 */
const StackPolicy = Object.freeze({
  REFRESH: 'refresh',
  INTENSITY: 'intensity',
  DURATION: 'duration',
  INDEPENDENT: 'independent',
});

/**
 * Validated status-effect definition and mutable applied instance factory.
 */
class StatusEffect {
  /**
   * @param {object} options Effect definition.
   */
  constructor({
    id,
    duration = 5,
    tickInterval = 1,
    maxStacks = 1,
    stackPolicy = StackPolicy.REFRESH,
    isDebuff = true,
    tags = [],
    modifiers = [],
    onTick = null,
    metadata = {},
  } = {}) {
    if (!id) throw new TypeError('A status effect requires an identifier.');
    if (!Number.isFinite(duration) || duration < 0) throw new RangeError('Effect duration must be non-negative.');
    if (!Number.isFinite(tickInterval) || tickInterval < 0) throw new RangeError('Effect tick interval must be non-negative.');
    if (!Number.isInteger(maxStacks) || maxStacks < 1) throw new RangeError('Maximum effect stacks must be a positive integer.');
    if (!Object.values(StackPolicy).includes(stackPolicy)) throw new RangeError(`Unknown stack policy: ${stackPolicy}.`);
    if (onTick !== null && typeof onTick !== 'function') throw new TypeError('An effect tick handler must be a function.');
    this.id = String(id);
    this.duration = duration;
    this.tickInterval = tickInterval;
    this.maxStacks = maxStacks;
    this.stackPolicy = stackPolicy;
    this.isDebuff = Boolean(isDebuff);
    this.tags = [...tags];
    this.modifiers = modifiers.map((modifier) => ({ ...modifier }));
    this.onTick = onTick;
    this.metadata = { ...metadata };
  }

  /**
   * Creates an independent mutable application instance.
   *
   * @param {string} [instanceId=this.id] Unique application identifier.
   * @returns {object} Effect instance.
   */
  createInstance(instanceId = this.id) {
    return {
      instanceId,
      id: this.id,
      duration: this.duration,
      remaining: this.duration,
      tickInterval: this.tickInterval,
      accumulator: 0,
      stacks: 1,
      maxStacks: this.maxStacks,
      stackPolicy: this.stackPolicy,
      isDebuff: this.isDebuff,
      tags: [...this.tags],
      modifiers: this.modifiers.map((modifier) => ({ ...modifier })),
      onTick: this.onTick,
      metadata: { ...this.metadata },
    };
  }
}

/**
 * Frame-rate independent active status-effect manager.
 */
class StatusEffectManager {
  /**
   * @param {object} target Target entity that owns attributes and optional events.
   */
  constructor(target) {
    this.target = target ?? null;
    this.effects = new Map();
    this.nextInstanceNumber = 1;
  }

  /**
   * Applies an effect definition, observing its chosen stack policy.
   *
   * @param {StatusEffect|object} definition Effect definition.
   * @returns {object} Active effect instance.
   */
  apply(definition) {
    const effect = definition instanceof StatusEffect ? definition : new StatusEffect(definition);
    const existing = this.findByLogicalId(effect.id);
    if (effect.stackPolicy !== StackPolicy.INDEPENDENT && existing) {
      this.reapply(existing, effect);
      return existing;
    }
    const instanceId = effect.stackPolicy === StackPolicy.INDEPENDENT
      ? `${effect.id}#${this.nextInstanceNumber++}`
      : effect.id;
    const instance = effect.createInstance(instanceId);
    this.effects.set(instanceId, instance);
    this.applyModifiers(instance);
    this.emit(EnvironmentEvents.EFFECT_APPLIED, instance);
    return instance;
  }

  /**
   * Removes an effect by instance or logical identifier.
   *
   * @param {string} id Effect identifier.
   * @returns {boolean} Whether an effect was removed.
   */
  remove(id) {
    const entries = [...this.effects.entries()].filter(([instanceId, effect]) => instanceId === id || effect.id === id);
    for (const [instanceId, effect] of entries) {
      this.removeModifiers(effect);
      this.effects.delete(instanceId);
      this.emit(EnvironmentEvents.EFFECT_REMOVED, effect);
    }
    return entries.length > 0;
  }

  /**
   * Removes all effects tagged with a value.
   *
   * @param {string} tag Tag to dispel.
   * @returns {number} Number of removed effects.
   */
  dispelByTag(tag) {
    const ids = [...this.effects.values()].filter((effect) => effect.tags.includes(tag)).map((effect) => effect.instanceId);
    for (const id of ids) this.remove(id);
    return ids.length;
  }

  /**
   * Removes every active debuff.
   *
   * @returns {number} Number of removed effects.
   */
  dispelAllDebuffs() {
    const ids = [...this.effects.values()].filter((effect) => effect.isDebuff).map((effect) => effect.instanceId);
    for (const id of ids) this.remove(id);
    return ids.length;
  }

  /**
   * Advances durations and processes every elapsed tick interval without drift.
   *
   * @param {number} deltaSeconds Simulation delta.
   */
  update(deltaSeconds) {
    if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) {
      throw new RangeError('Effect delta seconds must be finite and non-negative.');
    }
    for (const [instanceId, effect] of [...this.effects]) {
      const activeDelta = Math.min(deltaSeconds, Math.max(0, effect.remaining));
      effect.remaining -= deltaSeconds;
      effect.accumulator += activeDelta;
      if (effect.tickInterval > 0) {
        while (effect.accumulator + Number.EPSILON >= effect.tickInterval) {
          effect.accumulator -= effect.tickInterval;
          effect.onTick?.(this.target, effect.stacks, effect);
        }
      }
      if (effect.remaining <= 0) this.remove(instanceId);
    }
  }

  /** @returns {Array<object>} Persistable active effect state. */
  serialise() {
    return [...this.effects.values()].map((effect) => ({
      ...effect,
      tags: [...effect.tags],
      modifiers: effect.modifiers.map((modifier) => ({ ...modifier })),
      onTick: undefined,
    }));
  }

  /**
   * Finds the non-independent active effect for a logical identifier.
   *
   * @param {string} id Logical effect identifier.
   * @returns {object|undefined} Active instance.
   */
  findByLogicalId(id) {
    return [...this.effects.values()].find((effect) => effect.id === id && effect.stackPolicy !== StackPolicy.INDEPENDENT);
  }

  /**
   * Applies the correct reapplication behaviour.
   *
   * @param {object} instance Existing effect instance.
   * @param {StatusEffect} definition Incoming definition.
   */
  reapply(instance, definition) {
    if (instance.stackPolicy === StackPolicy.REFRESH) instance.remaining = definition.duration;
    if (instance.stackPolicy === StackPolicy.INTENSITY) {
      instance.stacks = Math.min(instance.maxStacks, instance.stacks + 1);
      instance.remaining = definition.duration;
      this.applyModifiers(instance);
    }
    if (instance.stackPolicy === StackPolicy.DURATION) {
      instance.remaining += definition.duration;
    }
  }

  /**
   * Attaches stack-scaled attribute modifiers.
   *
   * @param {object} effect Effect instance.
   */
  applyModifiers(effect) {
    this.removeModifiers(effect);
    effect.modifiers.forEach((modifier, index) => {
      const attribute = this.target?.getAttribute?.(modifier.attribute);
      if (!attribute) return;
      attribute.addModifier(new StatModifier({
        id: `${effect.instanceId}:${index}`,
        type: modifier.type,
        value: Number(modifier.value) * effect.stacks,
        source: `effect:${effect.instanceId}`,
      }));
    });
  }

  /**
   * Detaches every modifier installed by an effect.
   *
   * @param {object} effect Effect instance.
   */
  removeModifiers(effect) {
    effect.modifiers.forEach((modifier, index) => {
      this.target?.getAttribute?.(modifier.attribute)?.removeModifier(`${effect.instanceId}:${index}`);
    });
  }

  /**
   * Emits using either the conventional target emitter or an event bus shape.
   *
   * @param {string} event Event name.
   * @param {object} effect Effect state.
   */
  emit(event, effect) {
    this.target?.emit?.(event, effect);
    if (event === EnvironmentEvents.EFFECT_APPLIED) this.target?.emit?.('onEffectApplied', effect);
    if (event === EnvironmentEvents.EFFECT_REMOVED) this.target?.emit?.('onEffectRemoved', effect);
  }
}

/**
 * Deterministic experience requirement curve.
 */
class ExperienceCurve {
  /**
   * @param {object} [options] Curve configuration.
   * @param {'exponential'|'polynomial'} [options.mode='exponential'] Curve form.
   * @param {number} [options.baseXP=100] Base experience requirement.
   * @param {number} [options.exponent=1.6] Level exponent.
   * @param {number} [options.flatStep=40] Linear step per completed level.
   */
  constructor({ mode = 'exponential', baseXP = 100, exponent = 1.6, flatStep = 40 } = {}) {
    if (!['exponential', 'polynomial'].includes(mode)) throw new RangeError(`Unknown experience curve mode: ${mode}.`);
    if (![baseXP, exponent, flatStep].every(Number.isFinite) || baseXP <= 0 || exponent <= 0) {
      throw new RangeError('Experience curve constants must be positive finite values.');
    }
    this.mode = mode;
    this.baseXP = baseXP;
    this.exponent = exponent;
    this.flatStep = flatStep;
  }

  /**
   * Gets experience required to advance from one level.
   *
   * @param {number} level Current level.
   * @param {number} [maxLevel=Infinity] Optional level ceiling.
   * @returns {number} Required experience, or Infinity at the ceiling.
   */
  getRequirement(level, maxLevel = Infinity) {
    if (!Number.isInteger(level) || level < 1) throw new RangeError('Experience level must be a positive integer.');
    if (level >= maxLevel) return Infinity;
    const power = this.mode === 'polynomial'
      ? level * level * this.exponent
      : level ** this.exponent;
    return Math.max(1, Math.floor(this.baseXP * power + this.flatStep * (level - 1)));
  }

  /** @returns {object} Persistable curve configuration. */
  serialise() { return { mode: this.mode, baseXP: this.baseXP, exponent: this.exponent, flatStep: this.flatStep }; }
}

/**
 * Character level, experience rollover, attribute growth, and perk tracking.
 */
class CharacterProgression {
  /**
   * @param {object} [options] Progression configuration.
   */
  constructor({
    targetCharacter,
    maxLevel = 50,
    level = 1,
    currentXP = 0,
    curve,
    mode,
    baseXP,
    exponent,
    flatStep,
    statGrowths = {},
    unspentPerkPoints = 0,
  } = {}) {
    if (!Number.isInteger(maxLevel) || maxLevel < 1) throw new RangeError('Maximum level must be a positive integer.');
    if (!Number.isInteger(level) || level < 1 || level > maxLevel) throw new RangeError('Initial level is out of range.');
    this.target = targetCharacter ?? null;
    this.maxLevel = maxLevel;
    this.level = level;
    this.currentXP = Math.max(0, Number(currentXP) || 0);
    this.curve = curve ?? new ExperienceCurve({ mode, baseXP, exponent, flatStep });
    this.statGrowths = { ...statGrowths };
    this.unspentPerkPoints = Math.max(0, Number(unspentPerkPoints) || 0);
    this.resolveLevelUps();
  }

  /** @returns {number} Experience needed for the next level. */
  get nextLevelXP() { return this.getXPForLevel(this.level); }

  /**
   * Gets the requirement for a level transition.
   *
   * @param {number} level Current level.
   * @returns {number} Required experience.
   */
  getXPForLevel(level) { return this.curve.getRequirement(level, this.maxLevel); }

  /**
   * Grants non-negative experience and preserves all multi-level overflow.
   *
   * @param {number} amount Experience to grant.
   * @returns {{levelsGained: number, currentXP: number, level: number}} Grant result.
   */
  grantXP(amount) {
    if (!Number.isFinite(amount) || amount < 0) throw new RangeError('Granted experience must be non-negative and finite.');
    this.currentXP += amount;
    const levelsGained = this.resolveLevelUps();
    return { levelsGained, currentXP: this.currentXP, level: this.level };
  }

  /**
   * Spends one available perk point.
   *
   * @returns {boolean} Whether a point was spent.
   */
  spendPerkPoint() {
    if (this.unspentPerkPoints <= 0) return false;
    this.unspentPerkPoints -= 1;
    return true;
  }

  /**
   * Consumes level requirements until no further level can be gained.
   *
   * @returns {number} Number of gained levels.
   */
  resolveLevelUps() {
    let levelsGained = 0;
    while (this.level < this.maxLevel) {
      const requirement = this.getXPForLevel(this.level);
      if (this.currentXP < requirement) break;
      this.currentXP -= requirement;
      this.level += 1;
      this.unspentPerkPoints += 1;
      levelsGained += 1;
      this.applyGrowth();
      this.target?.emit?.(EnvironmentEvents.LEVEL_UP, { level: this.level, points: this.unspentPerkPoints });
      this.target?.emit?.('onLevelUp', { level: this.level, points: this.unspentPerkPoints });
    }
    return levelsGained;
  }

  /**
   * Adds configured growth to base attributes without disturbing modifiers.
   */
  applyGrowth() {
    for (const [name, growth] of Object.entries(this.statGrowths)) {
      const attribute = this.target?.getAttribute?.(name);
      if (attribute) attribute.setBase(attribute.base + Number(growth));
    }
  }

  /** @returns {object} Persistable progression state. */
  serialise() {
    return {
      maxLevel: this.maxLevel,
      level: this.level,
      currentXP: this.currentXP,
      curve: this.curve.serialise(),
      statGrowths: { ...this.statGrowths },
      unspentPerkPoints: this.unspentPerkPoints,
    };
  }

  /**
   * Restores progression around a target character.
   *
   * @param {object} state Saved progression state.
   * @param {object} [options] Additional constructor options.
   * @returns {CharacterProgression} Restored progression.
   */
  static deserialise(state, options = {}) {
    return new CharacterProgression({ ...state, ...options, curve: new ExperienceCurve(state.curve) });
  }
}

/**
 * Ordered forward-only schema migration registry.
 */
class SchemaMigrator {
  /**
   * @param {number} [currentVersion=1] Latest supported schema version.
   */
  constructor(currentVersion = 1) {
    if (!Number.isInteger(currentVersion) || currentVersion < 1) {
      throw new RangeError('Current schema version must be a positive integer.');
    }
    this.currentVersion = currentVersion;
    this.migrations = new Map();
  }

  /**
   * Registers the migration from one version to its next version.
   *
   * @param {number} fromVersion Source version.
   * @param {(state: object) => object} migrate Forward migration function.
   * @returns {SchemaMigrator} This migrator.
   */
  register(fromVersion, migrate) {
    if (!Number.isInteger(fromVersion) || fromVersion < 1 || fromVersion >= this.currentVersion) {
      throw new RangeError('Migration source version is outside the supported range.');
    }
    if (typeof migrate !== 'function') throw new TypeError('A schema migration must be a function.');
    if (this.migrations.has(fromVersion)) throw new Error(`A migration from version ${fromVersion} already exists.`);
    this.migrations.set(fromVersion, migrate);
    return this;
  }

  /**
   * Migrates a snapshot to the current version without mutating its input.
   *
   * @param {object} input State with a version field.
   * @returns {object} Migrated state.
   */
  migrate(input) {
    if (!input || typeof input !== 'object') throw new TypeError('Serialised state must be an object.');
    let state = structuredClone(input);
    let version = Number(state.version ?? 1);
    if (!Number.isInteger(version) || version < 1) throw new RangeError('Serialised state has an invalid schema version.');
    if (version > this.currentVersion) throw new RangeError('Serialised state uses a newer schema version.');
    while (version < this.currentVersion) {
      const migration = this.migrations.get(version);
      if (!migration) throw new Error(`No forward migration exists from schema version ${version}.`);
      state = migration(structuredClone(state));
      version += 1;
      state.version = version;
    }
    return state;
  }
}

/**
 * Versioned JSON serialiser for environment and character state.
 */
class EnvironmentSerialiser {
  /**
   * @param {object} [options] Serialisation configuration.
   * @param {number} [options.version=1] Current schema version.
   * @param {SchemaMigrator} [options.migrator] Forward migration registry.
   */
  constructor({ version = 1, migrator } = {}) {
    this.version = version;
    this.migrator = migrator ?? new SchemaMigrator(version);
  }

  /**
   * Creates a lossless schema-versioned snapshot.
   *
   * @param {object} state Environment state containing optional world and character values.
   * @returns {object} Plain snapshot.
   */
  snapshot({ world = {}, character = {}, metadata = {} } = {}) {
    return {
      version: this.version,
      world: EnvironmentSerialiser.toPlain(world),
      character: EnvironmentSerialiser.toPlain(character),
      metadata: EnvironmentSerialiser.toPlain(metadata),
    };
  }

  /**
   * Serialises a snapshot to compact JSON.
   *
   * @param {object} state Environment state.
   * @returns {string} JSON payload.
   */
  serialise(state) { return JSON.stringify(EnvironmentSerialiser.encodeForJson(this.snapshot(state))); }

  /**
   * Parses and migrates state to the current schema.
   *
   * @param {string|object} input JSON string or plain snapshot.
   * @returns {object} Migrated snapshot.
   */
  deserialise(input) {
    const parsed = typeof input === 'string' ? EnvironmentSerialiser.decodeFromJson(JSON.parse(input)) : input;
    return this.migrator.migrate(parsed);
  }

  /**
   * Converts nested serialisable objects to JSON-safe data.
   *
   * @param {unknown} value Value to copy.
   * @returns {unknown} Plain value.
   */
  static toPlain(value) {
    if (value && typeof value.serialise === 'function') return EnvironmentSerialiser.toPlain(value.serialise());
    if (Array.isArray(value)) return value.map((entry) => EnvironmentSerialiser.toPlain(entry));
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, EnvironmentSerialiser.toPlain(entry)]));
    }
    return value;
  }

  /**
   * Replaces JavaScript values that JSON cannot represent with tagged objects.
   *
   * @param {unknown} value Plain state value.
   * @returns {unknown} JSON-safe value.
   */
  static encodeForJson(value) {
    if (value === Infinity) return { $littleEnvironmentType: 'positive-infinity' };
    if (value === -Infinity) return { $littleEnvironmentType: 'negative-infinity' };
    if (Number.isNaN(value)) return { $littleEnvironmentType: 'not-a-number' };
    if (value === undefined) return { $littleEnvironmentType: 'undefined' };
    if (Array.isArray(value)) return value.map((entry) => EnvironmentSerialiser.encodeForJson(entry));
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, EnvironmentSerialiser.encodeForJson(entry)]));
    }
    return value;
  }

  /**
   * Restores JavaScript values tagged by `encodeForJson`.
   *
   * @param {unknown} value Parsed JSON value.
   * @returns {unknown} Restored plain value.
   */
  static decodeFromJson(value) {
    if (Array.isArray(value)) return value.map((entry) => EnvironmentSerialiser.decodeFromJson(entry));
    if (value && typeof value === 'object') {
      const type = value.$littleEnvironmentType;
      if (type === 'positive-infinity') return Infinity;
      if (type === 'negative-infinity') return -Infinity;
      if (type === 'not-a-number') return Number.NaN;
      if (type === 'undefined') return undefined;
      return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, EnvironmentSerialiser.decodeFromJson(entry)]));
    }
    return value;
  }
}



export { EnvironmentEventBus, EnvironmentEvents, CalendarEngine, CelestialClock, AmbientColorGradient, LightSource, LightingCompositor, ClimateMatrix, PrecipitationParticle, WeatherSystem, HeatSource, ThermodynamicModel, SurvivalVitalManager, ModifierType, StatModifier, Attribute, DamagePayload, CombatResolver, StackPolicy, StatusEffect, StatusEffectManager, ExperienceCurve, CharacterProgression, SchemaMigrator, EnvironmentSerialiser };
