import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { manglePrivateIdentifiers, minifyJavaScript } from './minify.js';

const toolDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.resolve(toolDirectory, '..');
const importPattern = /^\s*import\s+[^;]+?\s+from\s+['"]([^'"]+)['"];?\s*$/gm;
const reExportPattern = /^\s*export\s*\{\s*([^}]+)\s*\}\s*from\s*['"]([^'"]+)['"];?\s*$/gm;

/**
 * Bundles LittleEnvironment's dependency-free ESM modules into release artefacts.
 *
 * @returns {Promise<{unminifiedPath: string, minifiedPath: string, sourceMapPath: string}>} Output paths.
 */
export async function build() {
  const entryPath = path.join(projectDirectory, 'src', 'index.js');
  const releaseDirectory = path.join(projectDirectory, 'release');
  const orderedModules = [];
  const visited = new Set();
  const publicExports = [];

  async function collect(filePath, isEntry = false) {
    const absolutePath = path.resolve(filePath);
    if (visited.has(absolutePath)) return;
    visited.add(absolutePath);
    let source = await fs.readFile(absolutePath, 'utf8');
    const reExports = [...source.matchAll(reExportPattern)];
    for (const match of reExports) {
      if (isEntry) publicExports.push(...match[1].split(',').map((name) => name.trim()).filter(Boolean));
      const dependencyPath = path.resolve(path.dirname(absolutePath), match[2]);
      await collect(dependencyPath);
    }
    const imports = [...source.matchAll(importPattern)];
    for (const match of imports) {
      if (!match[1].startsWith('.')) throw new Error(`External dependency found in ${absolutePath}.`);
      const dependencyPath = path.resolve(path.dirname(absolutePath), match[1]);
      await collect(dependencyPath);
    }
    source = source.replace(importPattern, '').replace(reExportPattern, '');
    if (!isEntry) source = source.replace(/^\s*export\s+/gm, '');
    orderedModules.push({ path: absolutePath, source });
  }

  await collect(entryPath, true);
  await fs.mkdir(releaseDirectory, { recursive: true });
  const banner = '/* LittleEnvironment v1.0.0 | Generated by tools/build.js */\n';
  const bundle = `${banner}${orderedModules.map((module) => module.source.trim()).join('\n\n')}\n\nexport { ${publicExports.join(', ')} };\n`;
  const unminifiedPath = path.join(releaseDirectory, 'littleenvironment.js');
  const minifiedPath = path.join(releaseDirectory, 'littleenvironment.min.js');
  const sourceMapPath = path.join(releaseDirectory, 'littleenvironment.min.js.map');
  const sourceMap = {
    version: 3,
    file: 'littleenvironment.min.js',
    sources: orderedModules.map((module) => path.relative(releaseDirectory, module.path).replaceAll(path.sep, '/')),
    sourcesContent: orderedModules.map((module) => module.source),
    names: [],
    mappings: '',
  };
  const minified = `${minifyJavaScript(manglePrivateIdentifiers(bundle))}\n//# sourceMappingURL=littleenvironment.min.js.map\n`;
  await Promise.all([
    fs.writeFile(unminifiedPath, bundle, 'utf8'),
    fs.writeFile(minifiedPath, minified, 'utf8'),
    fs.writeFile(sourceMapPath, JSON.stringify(sourceMap), 'utf8'),
  ]);
  return { unminifiedPath, minifiedPath, sourceMapPath };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build().then((paths) => console.log(`LittleEnvironment build completed: ${paths.minifiedPath}`));
}
